#!/usr/bin/env python3
"""Generate Wall Street-style research report for India and/or US markets.

Usage:
    python scripts/research_report.py                    # Both markets
    python scripts/research_report.py --market india      # India only
    python scripts/research_report.py --market us         # US only
    python scripts/research_report.py --capital 5000000   # Custom capital (INR)
    python scripts/research_report.py --output report.md  # Save to file
    python scripts/research_report.py --broker            # Use live broker data

Generates: regime scan, deployment plan, risk assessment, trade ideas, gaps.
Output: Markdown (publishable on LinkedIn, Medium, Substack).
"""
import sys
import io
import argparse
import warnings
import logging
from datetime import date, datetime
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
warnings.filterwarnings("ignore")
logging.disable(logging.WARNING)


# ── Universe definitions ──

INDIA_UNIVERSE = {
    "indices": ["NIFTY", "BANKNIFTY"],
    "it": ["TCS", "INFY", "WIPRO"],
    "banking": ["HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK"],
    "diversified": ["RELIANCE", "LT", "BAJFINANCE", "ITC", "HINDUNILVR", "TATAMOTORS"],
}

US_UNIVERSE = {
    "indices": ["SPY", "QQQ", "IWM", "DIA"],
    "sectors": ["XLF", "XLE", "XLK", "XLV"],
    "safe_havens": ["GLD", "TLT"],
    "mega_cap": ["AAPL", "MSFT", "NVDA", "AMZN", "META"],
}


def flatten(universe: dict) -> list[str]:
    tickers = []
    for group in universe.values():
        tickers.extend(group)
    return tickers


def get_signal(regime_id: int, rsi: float) -> str:
    if regime_id == 4:
        return "AVOID"
    if regime_id == 3 and rsi < 35:
        return "WATCH (oversold in trend)"
    if regime_id == 3:
        return "CAUTION"
    if regime_id in (1, 2) and rsi < 30:
        return "OPPORTUNITY"
    if regime_id in (1, 2) and rsi < 40:
        return "BUILDING"
    return "NORMAL"


def scan_market(ma, tickers: list[str], market_label: str) -> list[dict]:
    """Scan tickers and return regime + technical data."""
    results = []
    for t in tickers:
        try:
            r = ma.regime.detect(t)
            tech = ma.technicals.snapshot(t)

            # IV rank (broker only)
            ivr = None
            try:
                m = ma.quotes.get_metrics(t)
                if m and hasattr(m, "iv_rank") and m.iv_rank:
                    ivr = m.iv_rank
                elif isinstance(m, dict) and m.get("ivRank"):
                    ivr = m["ivRank"]
            except Exception:
                pass

            results.append({
                "ticker": t,
                "regime": r.regime.value,
                "confidence": r.confidence,
                "rsi": tech.rsi.value,
                "atr_pct": tech.atr_pct,
                "price": tech.current_price,
                "iv_rank": ivr,
                "signal": get_signal(r.regime.value, tech.rsi.value),
                "bb_pct_b": tech.bollinger.percent_b if tech.bollinger else None,
            })
        except Exception as e:
            results.append({"ticker": t, "error": str(e)[:60]})
    return results


def generate_report(
    market: str,
    india_data: list[dict] | None,
    us_data: list[dict] | None,
    capital_india: float,
    capital_us: float,
    sentinel_signal: str,
    sentinel_reasons: list[str],
    has_broker: bool,
) -> str:
    """Generate the markdown research report."""
    today = date.today().strftime("%B %d, %Y")
    lines = []

    def w(line=""):
        lines.append(line)

    w("# INCOME DESK RESEARCH")
    w(f"## Global Markets: Equity Income Strategy — Deployment Readiness")
    w(f"### {today}")
    w()
    w(f"**Generated by:** income-desk Systematic Intelligence")
    w(f"**Data:** {'TastyTrade DXLink + ' if has_broker else ''}yfinance Historical OHLCV + HMM 4-State Regime Model")
    w(f"**Trust:** {'HIGH (broker connected)' if has_broker else 'MEDIUM (no broker — IV rank unavailable)'}")
    w()
    w("---")
    w()

    # Crash sentinel
    w("### MARKET HEALTH")
    w()
    w(f"**Crash Sentinel: {sentinel_signal.upper()}**")
    for r in sentinel_reasons:
        w(f"- {r}")
    w()

    # ── India Section ──
    if india_data:
        w("---")
        w()
        w(f"## INDIA MARKET (Capital: INR {capital_india:,.0f})")
        w()

        # Regime table
        r4_count = sum(1 for d in india_data if d.get("regime") == 4)
        r1_count = sum(1 for d in india_data if d.get("regime") == 1)
        r2_count = sum(1 for d in india_data if d.get("regime") == 2)

        w(f"**Regime summary:** {r4_count} R4 (explosive), {r2_count} R2 (volatile MR), {r1_count} R1 (calm)")
        w()
        w("| Ticker | Regime | Conf | RSI | ATR% | IV Rank | Signal | Commentary |")
        w("|--------|--------|------|-----|------|---------|--------|------------|")

        for d in india_data:
            if "error" in d:
                w(f"| {d['ticker']} | — | — | — | — | — | ERROR | {d['error']} |")
                continue
            ivr = f"{d['iv_rank']:.0f}%" if d.get("iv_rank") else "N/A"
            commentary = _india_commentary(d)
            w(f"| {'**' + d['ticker'] + '**' if d['signal'] in ('OPPORTUNITY', 'AVOID') else d['ticker']} "
              f"| {'**R' + str(d['regime']) + '**' if d['regime'] == 4 else 'R' + str(d['regime'])} "
              f"| {d['confidence']:.0%} | {d['rsi']:.1f} | {d['atr_pct']:.2f} "
              f"| {ivr} | {d['signal']} | {commentary} |")

        w()

        # India verdict
        nifty = next((d for d in india_data if d["ticker"] == "NIFTY" and "regime" in d), None)
        if nifty and nifty["regime"] == 4:
            w("### INDIA VERDICT: WAIT")
            w()
            w(f"NIFTY is R4 at {nifty['confidence']:.0%} confidence. This is an explosive regime — "
              f"income structures on the index will face max-loss events. "
              f"Daily ATR of {nifty['atr_pct']:.1f}% implies ±{nifty['price'] * nifty['atr_pct'] / 100:.0f} point swings.")
            w()
            w("**Do not deploy on indices until NIFTY transitions to R2.**")
        elif nifty and nifty["regime"] == 2:
            w("### INDIA VERDICT: SELECTIVE DEPLOYMENT")
            w()
            w("NIFTY is R2 — the correction is maturing. Premium is elevated. "
              "Deploy on indices with wider wings and R2 regime stop (3.0× credit).")
        elif nifty and nifty["regime"] == 1:
            w("### INDIA VERDICT: FULL DEPLOYMENT")
            w()
            w("NIFTY is R1 — calm, mean-reverting. This is the ideal income environment. Deploy fully.")

        w()

        # ── EXISTING POSITION HOLDERS ──
        w("### If You Already Have Positions (India)")
        w()
        w("| Your Position | Current Regime | Action | Urgency | Detail |")
        w("|--------------|----------------|--------|---------|--------|")
        for d in india_data:
            if "error" in d:
                continue
            t, r, rsi, atr = d["ticker"], d["regime"], d["rsi"], d["atr_pct"]
            if r == 4:
                w(f"| {t} IC/spread | **R4** | **CLOSE** | Immediate | R4 destroys income structures. Close at market. Take the loss. Capital preservation > hope. |")
                w(f"| {t} equity | **R4** | **HEDGE or HOLD** | Today | If long-term hold: add NIFTY put hedge. If trading position: close. ATR {atr:.1f}% = daily ±{d['price']*atr/100:.0f} moves. |")
            elif r == 3:
                w(f"| {t} IC/spread | R3 trend | **CONVERT** | Soon | Trend persists. Convert IC → diagonal in trend direction. Or close tested side. Stop at 1.5× credit. |")
                if rsi < 30:
                    w(f"| {t} equity | R3 oversold | **HOLD + HEDGE** | This week | RSI {rsi:.0f} oversold but trend is down. Add collar if lot size permits. Do NOT average down. |")
                else:
                    w(f"| {t} equity | R3 trend | **TIGHTEN STOP** | This week | Set stop at recent swing low. Do not add. |")
            elif r == 2:
                w(f"| {t} IC/spread | R2 vol MR | **HOLD** (wider stop) | Monitor | R2 swings are wide but revert. Use 3.0× regime stop, not 2.0×. Don't panic on intraday spike. |")
                w(f"| {t} equity | R2 | **HOLD** | Monitor | Mean-reverting vol. If profitable: consider selling covered call for income. |")
            elif r == 1:
                if rsi < 35:
                    w(f"| {t} IC/spread | R1 + oversold | **HOLD** (textbook) | None | Perfect income environment. Let theta work. Standard 2.0× stop. |")
                else:
                    w(f"| {t} IC/spread | R1 calm | **HOLD** | None | Calm regime. Structures working as designed. |")
        w()

        # ── NEW POSITION IDEAS ──
        w("### New Position Ideas (India)")
        w()
        opportunities = [d for d in india_data if d.get("signal") in ("OPPORTUNITY", "BUILDING") and "regime" in d]
        avoids = [d for d in india_data if d.get("signal") == "AVOID" and "regime" in d]

        if not opportunities:
            w("**No immediate opportunities.** All R1/R2 tickers are above oversold threshold. Wait for RSI < 30 on R1 names or regime transition on R2 names.")
        else:
            w("| Ticker | Regime | RSI | Setup | Structure | Entry Trigger | Risk |")
            w("|--------|--------|-----|-------|-----------|---------------|------|")
            for d in opportunities:
                t, r, rsi = d["ticker"], d["regime"], d["rsi"]
                if r == 1 and rsi < 30:
                    w(f"| **{t}** | R1 | {rsi:.0f} | **Income entry** | Credit spread or CSP | RSI < 27 confirms | Max 1 lot, quarter Kelly |")
                elif r == 1 and rsi < 40:
                    w(f"| {t} | R1 | {rsi:.0f} | Building | Credit spread | Wait for RSI < 30 | Not yet — patience |")
                elif r == 2 and rsi < 35:
                    w(f"| {t} | R2 | {rsi:.0f} | Approaching | Wider IC (1.5× ATR) | RSI < 30 + R2 confirmed | Shorter DTE (21), 3× stop |")
                elif r == 2:
                    w(f"| {t} | R2 | {rsi:.0f} | Monitoring | — | Wait for oversold | Not ready |")
        w()

        if avoids:
            w("**Avoid these (R4):** " + ", ".join(f"{d['ticker']} (ATR {d['atr_pct']:.1f}%)" for d in avoids))
            w()

        # Deployment phases
        w("### India Deployment Plan")
        w()
        w("| Phase | Trigger | Deploy | Instruments |")
        w("|-------|---------|--------|-------------|")
        w(f"| 0 | Now | INR 0 (0%) | 100% cash. Monitor daily. |")

        # Find best opportunities for phased deployment
        phase1_candidates = [d for d in india_data if d.get("regime") == 1 and d.get("rsi", 50) < 35]
        phase2_candidates = [d for d in india_data if d.get("regime") == 2 and d.get("rsi", 50) < 38]

        if phase1_candidates:
            names = ", ".join(d["ticker"] for d in phase1_candidates[:2])
            w(f"| 1 | R1 tickers RSI < 27 | INR {capital_india * 0.12:,.0f} (12%) | {names} credit spread |")

        w(f"| 2 | NIFTY R4 → R2 | INR {capital_india * 0.24:,.0f} (24%) | NIFTY IC + R2 stocks |")
        w(f"| 3 | NIFTY R2 → R1 | INR {capital_india * 0.24:,.0f} (24%) | Full NIFTY/BANKNIFTY IC |")
        w(f"| 4 | Full deployment | INR {capital_india * 0.24:,.0f} (24%) | Core equity + metals |")
        w(f"| R | Reserve | INR {capital_india * 0.16:,.0f} (16%) | Permanent cash buffer |")
        w()

    # ── US Section ──
    if us_data:
        w("---")
        w()
        w(f"## US MARKET (Capital: ${capital_us:,.0f})")
        w()

        r4_count = sum(1 for d in us_data if d.get("regime") == 4)
        r1_count = sum(1 for d in us_data if d.get("regime") == 1)

        w(f"**Regime summary:** {r4_count} R4, {r1_count} R1 (tradeable now)")
        w()
        w("| Ticker | Regime | Conf | RSI | ATR% | IV Rank | Signal | Commentary |")
        w("|--------|--------|------|-----|------|---------|--------|------------|")

        for d in us_data:
            if "error" in d:
                w(f"| {d['ticker']} | — | — | — | — | — | ERROR | {d['error']} |")
                continue
            ivr = f"{d['iv_rank']:.0f}%" if d.get("iv_rank") else "N/A"
            commentary = _us_commentary(d)
            w(f"| {'**' + d['ticker'] + '**' if d['signal'] in ('OPPORTUNITY', 'AVOID') else d['ticker']} "
              f"| {'**R' + str(d['regime']) + '**' if d['regime'] == 4 else 'R' + str(d['regime'])} "
              f"| {d['confidence']:.0%} | {d['rsi']:.1f} | {d['atr_pct']:.2f} "
              f"| {ivr} | {d['signal']} | {commentary} |")

        w()

        # ── EXISTING POSITION HOLDERS (US) ──
        w("### If You Already Have Positions (US)")
        w()
        w("| Your Position | Current Regime | Action | Urgency | Detail |")
        w("|--------------|----------------|--------|---------|--------|")
        for d in us_data:
            if "error" in d:
                continue
            t, r, rsi, atr = d["ticker"], d["regime"], d["rsi"], d["atr_pct"]
            ivr = d.get("iv_rank", 0) or 0
            if r == 4:
                w(f"| {t} IC/spread | **R4** | **CLOSE** | Immediate | Explosive regime. Close at market. No adjustments — just exit. |")
                w(f"| {t} equity | **R4** | **HEDGE** | Today | Add SPY put or collar. ATR {atr:.1f}% = violent moves. |")
            elif r == 3:
                w(f"| {t} IC/spread | R3 trend | **CLOSE or CONVERT** | Soon | Convert to diagonal if profitable side exists. Otherwise close. 1.5× stop. |")
                if rsi < 30:
                    w(f"| {t} equity | R3 + RSI {rsi:.0f} | **HOLD** (oversold) | Monitor | Deeply oversold in trend. Don't add but don't panic sell. Tighten stop. |")
            elif r == 2:
                w(f"| {t} IC/spread | R2 | **HOLD** (3× stop) | Monitor | R2 = wider swings that revert. Widen stop to 3.0× credit. Be patient. |")
                if ivr > 50:
                    w(f"| {t} equity | R2 + IVR {ivr:.0f}% | **SELL CC** | This week | IV rank elevated — sell covered call for income while holding. |")
            elif r == 1:
                w(f"| {t} IC/spread | R1 | **HOLD** | None | Ideal regime. Theta working for you. Standard 2.0× stop. |")
                if ivr > 40:
                    w(f"| {t} equity | R1 + IVR {ivr:.0f}% | **SELL CC** | This week | Good premium. Sell OTM call 30 DTE. |")
        w()

        # ── NEW POSITION IDEAS (US) ──
        w("### New Position Ideas (US)")
        w()
        us_opps = [d for d in us_data if d.get("regime") == 1 and d.get("iv_rank", 0) and d["iv_rank"] > 40]
        us_watch = [d for d in us_data if d.get("regime") in (2, 3) and d.get("iv_rank", 0) and d["iv_rank"] > 50 and d.get("rsi", 50) < 35]

        if us_opps:
            w("**Actionable now (R1 + IV Rank > 40%):**")
            w()
            w("| Ticker | Regime | IV Rank | RSI | Structure | Size | Entry |")
            w("|--------|--------|---------|-----|-----------|------|-------|")
            for d in us_opps:
                w(f"| **{d['ticker']}** | R1 | {d['iv_rank']:.0f}% | {d['rsi']:.0f} | IC or credit spread | 1-2 contracts, half Kelly | Limit at mid, patient |")
            w()

        if us_watch:
            w("**Watch for R2 transition (high IV, approaching oversold):**")
            w()
            for d in us_watch:
                w(f"- **{d['ticker']}** (R{d['regime']}, IV Rank {d['iv_rank']:.0f}%, RSI {d['rsi']:.0f}): "
                  f"When regime transitions to R2 → premium will be extraordinary. Set alert.")
            w()

        high_iv_r3 = [d for d in us_data if d.get("regime") == 3 and d.get("iv_rank", 0) and d["iv_rank"] > 55]
        if high_iv_r3:
            w("**Highest premium potential (waiting for regime transition):**")
            w()
            for d in high_iv_r3:
                w(f"- **{d['ticker']}** IV Rank {d['iv_rank']:.0f}% but R3 trending — when R2 arrives, this is the main trade")
            w()

        avoids_us = [d for d in us_data if d.get("regime") == 4 and "error" not in d]
        if avoids_us:
            w("**Avoid (R4):** " + ", ".join(f"{d['ticker']}" for d in avoids_us))
            w()

        # US deployment
        w("### US Deployment Plan")
        w()
        w("| Phase | Trigger | Deploy | Instruments |")
        w("|-------|---------|--------|-------------|")

        r1_names = [d["ticker"] for d in us_data if d.get("regime") == 1 and d.get("iv_rank", 0) and d["iv_rank"] > 35]
        if r1_names:
            w(f"| 0 | Now | ${capital_us * 0.15:,.0f} (15%) | {', '.join(r1_names[:3])} IC/spread |")
        else:
            w(f"| 0 | Now | $0 (0%) | No R1 + adequate IV — wait |")

        w(f"| 1 | SPY RSI < 28 | ${capital_us * 0.25:,.0f} (25%) | SPY IC (R2 wider wings) |")
        w(f"| 2 | GLD/IWM R3 → R2 | ${capital_us * 0.30:,.0f} (30%) | High-IV names in R2 |")
        w(f"| 3 | QQQ R3 → R2 | ${capital_us * 0.20:,.0f} (20%) | Tech sector recovery |")
        w(f"| R | Reserve | ${capital_us * 0.10:,.0f} (10%) | Permanent cash buffer |")
        w()

    # ── Cross-market ──
    if india_data and us_data:
        w("---")
        w()
        w("## CROSS-MARKET COMPARISON")
        w()

        india_r4 = sum(1 for d in india_data if d.get("regime") == 4)
        us_r4 = sum(1 for d in us_data if d.get("regime") == 4)

        w("| Dimension | India | US |")
        w("|-----------|-------|-----|")
        w(f"| R4 count | {india_r4}/{len(india_data)} | {us_r4}/{len(us_data)} |")
        w(f"| Index regime | {'R4 (crash)' if any(d.get('ticker') == 'NIFTY' and d.get('regime') == 4 for d in india_data) else 'R2-R3'} | {'R4' if any(d.get('ticker') == 'SPY' and d.get('regime') == 4 for d in us_data) else 'R2-R3'} |")
        w(f"| Deploy now? | {'NO — wait for R2' if india_r4 > 2 else 'SELECTIVE'} | {'SELECTIVE on R1 sectors' if us_r4 < 3 else 'NO'} |")
        w(f"| Best sector | {'IT (TCS R1)' if any(d.get('ticker') == 'TCS' and d.get('regime') == 1 for d in india_data) else 'None yet'} | {', '.join(d['ticker'] for d in us_data if d.get('regime') == 1)[:30] or 'None'} |")
        w()

    # ── Alerts ──
    w("---")
    w()
    w("## REGIME TRANSITION ALERTS TO SET")
    w()
    w("| Alert | Trigger | Action |")
    w("|-------|---------|--------|")
    if india_data:
        w("| NIFTY R4 → R2 | Regime model transition | Begin India Phase 2 deployment |")
        w("| TCS RSI < 27 | Technical threshold (in R1) | India Phase 1 — first trade |")
    if us_data:
        w("| GLD R3 → R2 | Regime + IV rank > 60% | US Phase 2 — extraordinary premium |")
        w("| SPY RSI < 28 | Technical threshold | US Phase 1 expansion |")
    w("| Sentinel → RED | Crash escalation | Close ALL income positions |")
    w()

    # ── Footer ──
    w("---")
    w()
    w("*This analysis is generated by income-desk, an open-source systematic trading intelligence system. "
      "Regime classifications are probabilistic. This is not financial advice. "
      f"Data trust: {'HIGH' if has_broker else 'MEDIUM'}.*")
    w()
    w(f"*Published: {today} | income-desk v1.0.0 | github.com/nitinblue/income-desk*")

    return "\n".join(lines)


def _india_commentary(d: dict) -> str:
    t, r, rsi, atr = d["ticker"], d["regime"], d["rsi"], d["atr_pct"]
    if r == 4:
        return f"Explosive. ATR {atr:.1f}% = violent moves. No exposure."
    if r == 3 and rsi < 30:
        return f"Deeply oversold but trend is down. Wait for R2."
    if r == 3:
        return f"Trending down. Not for income."
    if r == 1 and rsi < 30:
        return f"Oversold in calm regime — textbook income entry."
    if r == 1:
        return f"Calm. Standard income structures."
    if r == 2 and rsi < 35:
        return f"Approaching oversold in high-vol MR. Wider wings, shorter DTE."
    if r == 2:
        return f"High-vol MR. Premium elevated. Patience."
    return ""


def _us_commentary(d: dict) -> str:
    t, r, rsi, ivr = d["ticker"], d["regime"], d["rsi"], d.get("iv_rank", 0)
    if r == 4:
        return f"Explosive. Avoid."
    if r == 3 and rsi < 35:
        return f"Oversold in trend. Watch for R2 transition."
    if r == 3:
        return f"Trending. Wait."
    if r == 1 and ivr and ivr > 40:
        return f"R1 + IV rank {ivr:.0f}% — tradeable now."
    if r == 1:
        return f"Calm but IV rank {'low' if ivr and ivr < 30 else 'N/A'} — thin premium."
    if r == 2 and rsi < 32:
        return f"Approaching oversold in R2. Prepare entry."
    if r == 2:
        return f"R2 mean-reverting. Wider wings."
    return ""


def main():
    parser = argparse.ArgumentParser(description="Generate income-desk research report")
    parser.add_argument("--market", choices=["india", "us", "both"], default="both")
    parser.add_argument("--capital-india", type=float, default=5_000_000, help="India capital in INR")
    parser.add_argument("--capital-us", type=float, default=100_000, help="US capital in USD")
    parser.add_argument("--broker", action="store_true", help="Use live broker data")
    parser.add_argument("--output", type=str, default=None, help="Save to file (default: print)")
    args = parser.parse_args()

    # Connect data
    if args.broker:
        from income_desk.cli._broker import connect_broker
        md, mm, acct, wl = connect_broker(is_paper=False)
        if md is None:
            print("Broker connection failed.")
            return
        from income_desk import MarketAnalyzer, DataService
        ma = MarketAnalyzer(data_service=DataService(), market_data=md, market_metrics=mm)
        has_broker = True
    else:
        from income_desk import MarketAnalyzer, DataService
        ma = MarketAnalyzer(data_service=DataService())
        has_broker = False

    # Scan markets
    india_data = None
    us_data = None

    if args.market in ("india", "both"):
        print("Scanning India market...", file=sys.stderr)
        india_data = scan_market(ma, flatten(INDIA_UNIVERSE), "India")

    if args.market in ("us", "both"):
        print("Scanning US market...", file=sys.stderr)
        us_data = scan_market(ma, flatten(US_UNIVERSE), "US")

    # Crash sentinel (US-based)
    sentinel_signal = "GREEN"
    sentinel_reasons = ["All systems normal"]
    try:
        from income_desk.features.crash_sentinel import assess_crash_sentinel
        sentinel_regimes = {}
        sentinel_ivr = {}
        for t in ["SPY", "QQQ", "IWM", "GLD", "TLT"]:
            try:
                r = ma.regime.detect(t)
                sentinel_regimes[t] = {
                    "regime_id": r.regime.value,
                    "confidence": r.confidence,
                    "r4_prob": r.regime_probabilities.get(4, 0) if r.regime_probabilities else 0,
                }
                m = ma.quotes.get_metrics(t) if has_broker else None
                if m and hasattr(m, "iv_rank") and m.iv_rank:
                    sentinel_ivr[t] = m.iv_rank
            except Exception:
                pass

        if sentinel_regimes:
            tech = ma.technicals.snapshot("SPY")
            report = assess_crash_sentinel(
                sentinel_regimes, sentinel_ivr,
                spy_atr_pct=tech.atr_pct, spy_rsi=tech.rsi.value,
            )
            sentinel_signal = report.signal.value
            sentinel_reasons = report.reasons
    except Exception:
        pass

    # Generate report
    report = generate_report(
        market=args.market,
        india_data=india_data,
        us_data=us_data,
        capital_india=args.capital_india,
        capital_us=args.capital_us,
        sentinel_signal=sentinel_signal,
        sentinel_reasons=sentinel_reasons,
        has_broker=has_broker,
    )

    # Output
    if args.output:
        path = Path(args.output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(report, encoding="utf-8")
        print(f"Report saved: {path}", file=sys.stderr)
    else:
        print(report)

    # Also save to standard location
    research_dir = Path("docs/research")
    research_dir.mkdir(parents=True, exist_ok=True)
    dated_path = research_dir / f"{date.today().isoformat()}-deployment-analysis.md"
    dated_path.write_text(report, encoding="utf-8")
    print(f"Archived: {dated_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
