#!/usr/bin/env python3
"""Generate Wall Street-style research reports for India and/or US markets.

Usage:
    python scripts/research_report.py                    # Both markets
    python scripts/research_report.py --market india      # India only
    python scripts/research_report.py --market us         # US only
    python scripts/research_report.py --capital 5000000   # Custom capital (INR)
    python scripts/research_report.py --output report.md  # Save to file
    python scripts/research_report.py --broker            # Use live broker data

Generates: regime scan, deployment plan, risk assessment, trade ideas, gaps.
Output: Markdown (publishable on LinkedIn, Medium, Substack).

Each market produces a fully self-contained report — no cross-market references.
"""
import sys
import io
import argparse
import warnings
import logging
from datetime import date, datetime
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
warnings.filterwarnings("ignore")
logging.disable(logging.WARNING)


# ── Universe definitions ──

INDIA_UNIVERSE = {
    "indices": ["NIFTY", "BANKNIFTY"],
    "it": ["TCS", "INFY", "WIPRO"],
    "banking": ["HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK"],
    "diversified": ["RELIANCE", "LT", "BAJFINANCE", "ITC", "HINDUNILVR", "MARUTI"],
}

US_UNIVERSE = {
    "indices": ["SPY", "QQQ", "IWM", "DIA"],
    "sectors": ["XLF", "XLE", "XLK", "XLV"],
    "safe_havens": ["GLD", "TLT"],
    "mega_cap": ["AAPL", "MSFT", "NVDA", "AMZN", "META"],
}


def _safe_float(val, fmt=".1f", default="—"):
    """Format a float that might be None."""
    return f"{val:{fmt}}" if val is not None else default


def flatten(universe: dict) -> list[str]:
    tickers = []
    for group in universe.values():
        tickers.extend(group)
    return tickers


def get_signal(regime_id: int, rsi: float) -> str:
    if regime_id == 4:
        return "AVOID"
    if regime_id == 3 and rsi < 35:
        return "WATCH (oversold in trend)"
    if regime_id == 3:
        return "CAUTION"
    if regime_id in (1, 2) and rsi < 30:
        return "OPPORTUNITY"
    if regime_id in (1, 2) and rsi < 40:
        return "BUILDING"
    return "NORMAL"


def scan_market(ma, tickers: list[str], market_label: str) -> list[dict]:
    """Scan tickers and return regime + technical data."""
    results = []
    for t in tickers:
        try:
            r = ma.regime.detect(t)
            tech = ma.technicals.snapshot(t)

            # IV rank (broker only)
            ivr = None
            try:
                m = ma.quotes.get_metrics(t)
                if m and hasattr(m, "iv_rank") and m.iv_rank:
                    ivr = m.iv_rank
                elif isinstance(m, dict) and m.get("ivRank"):
                    ivr = m["ivRank"]
            except Exception:
                pass

            results.append({
                "ticker": t,
                "regime": r.regime.value,
                "confidence": r.confidence,
                "rsi": tech.rsi.value,
                "atr_pct": tech.atr_pct,
                "price": tech.current_price,
                "iv_rank": ivr,
                "signal": get_signal(r.regime.value, tech.rsi.value),
                "bb_pct_b": tech.bollinger.percent_b if tech.bollinger else None,
            })
        except Exception as e:
            results.append({
                "ticker": t, "error": str(e)[:60],
                "regime": 0, "confidence": 0.0, "rsi": 50.0,
                "atr_pct": 0.0, "price": 0.0, "iv_rank": None,
                "signal": "ERROR", "bb_pct_b": None,
            })
    return results


def _report_footer(lines, today, has_broker):
    """Append the standard footer to a report."""

    def w(line=""):
        lines.append(line)

    w("---")
    w()
    w("*This analysis is generated by income-desk, an open-source systematic trading intelligence system. "
      "Regime classifications are probabilistic. This is not financial advice. "
      f"Data trust: {'HIGH' if has_broker else 'MEDIUM'}.*")
    w()
    w(f"*Published: {today} | income-desk v1.0.0 | github.com/nitinblue/income-desk*")


# ---------------------------------------------------------------------------
# India report
# ---------------------------------------------------------------------------

def generate_india_report(
    ma,
    india_data: list[dict],
    capital_india: float,
    has_broker: bool,
) -> str:
    """Generate a self-contained India market research report."""
    today = date.today().strftime("%B %d, %Y")
    lines: list[str] = []

    def w(line=""):
        lines.append(line)

    w("# INCOME DESK RESEARCH — India Equity Income Strategy")
    w(f"### {today}")
    w()
    w(f"**Generated by:** income-desk Systematic Intelligence")
    w(f"**Data:** {'TastyTrade DXLink + ' if has_broker else ''}yfinance Historical OHLCV + HMM 4-State Regime Model")
    w(f"**Trust:** {'HIGH (broker connected)' if has_broker else 'MEDIUM (no broker — IV rank unavailable)'}")
    w()
    w("---")
    w()

    # ── MACRO ENVIRONMENT ──
    w("## MACRO ENVIRONMENT")
    w()

    # India VIX regime
    try:
        india_vix = ma.regime.detect("INDIAVIX")
        w(f"**India VIX:** R{india_vix.regime.value} (conf {india_vix.confidence:.0%})")
        if india_vix.regime.value >= 3:
            w(f"- India VIX in stress regime — widen wings, reduce position size")
        elif india_vix.regime.value <= 1:
            w(f"- India VIX calm — standard income deployment safe")
        w()
    except Exception:
        w("**India VIX:** Unavailable (insufficient data)")
        w()

    # RBI MPC proximity warning
    try:
        cal = ma.macro.calendar()
        if hasattr(cal, 'next_rbi') and cal.next_rbi:
            days = cal.days_to_next_rbi
            if days is not None and days <= 7:
                w(f"**\u26a0 RBI MPC in {days} day{'s' if days != 1 else ''}** ({cal.next_rbi.date.strftime('%b %d')})")
                w(f"- Avoid new NIFTY/BANKNIFTY income positions until after announcement")
                w(f"- Bank stocks (HDFCBANK, ICICIBANK, SBIN) will see IV crush post-decision")
                w()
            elif days is not None and days <= 14:
                w(f"**RBI MPC upcoming** ({cal.next_rbi.date.strftime('%b %d')}, {days} days)")
                w(f"- Consider shorter DTE for bank stock positions")
                w()
    except Exception:
        pass

    # Macro calendar — India events only (RBI MPC)
    try:
        cal = ma.macro.calendar()
        if hasattr(cal, 'events') and cal.events:
            india_events = [e for e in cal.events if e.event_type.value == "rbi_mpc"][:8]
            if india_events:
                w("**Upcoming Macro Events:**")
                w()
                w("| Date | Event | Impact | Options Impact |")
                w("|------|-------|--------|----------------|")
                for e in india_events:
                    w(f"| {e.date.strftime('%b %d')} | {e.name} | {e.impact.value.upper()} | {e.options_impact} |")
                w()
    except Exception:
        w("**Macro Calendar:** Unavailable")
        w()

    # Rate risk — India bank stocks
    try:
        from income_desk.features.rate_risk import assess_rate_risk
        rate_tickers = ["HDFCBANK", "ICICIBANK", "SBIN"]
        w("**Interest Rate Sensitivity:**")
        w()
        w("| Ticker | Rate Sensitivity | Impact per 100bp | Recommendation |")
        w("|--------|-----------------|------------------|----------------|")
        for rt in rate_tickers:
            try:
                rr = assess_rate_risk(rt)
                w(f"| {rt} | {rr.rate_sensitivity} | {rr.impact_per_100bp:.1%} | {rr.recommendation} |")
            except Exception:
                pass
        w()
    except Exception:
        w("**Rate Risk:** Unavailable")
        w()

    # Market narrative — India
    india_r4 = sum(1 for d in india_data if d.get("regime") == 4)

    w("### Market Narrative")
    w()
    if india_r4 >= 2:
        w("**India is in distress.** Both major indices (NIFTY, BANKNIFTY) are R4 — explosive, momentum-driven selling. "
          "This is not a pullback; it is a regime that persists until selling exhausts itself. "
          "Income structures on indices will face max-loss events. Cash is the correct position.")
        w()

    nifty = next((d for d in india_data if d.get("ticker") == "NIFTY" and "error" not in d), None)
    tcs = next((d for d in india_data if d.get("ticker") == "TCS" and "error" not in d), None)
    if nifty and tcs and nifty["regime"] == 4 and tcs["regime"] == 1:
        w(f"**Notable:** TCS is R1 (calm) while NIFTY is R4 (explosive). IT services are stabilizing before the "
          f"broader market — consistent with historical pattern where export-oriented, dollar-earning businesses "
          f"recover first. TCS is the first deployment candidate for India capital.")
        w()

    w("---")
    w()

    # ── Regime scan table ──
    w(f"## INDIA MARKET (Capital: INR {capital_india:,.0f})")
    w()

    r4_count = sum(1 for d in india_data if d.get("regime") == 4)
    r1_count = sum(1 for d in india_data if d.get("regime") == 1)
    r2_count = sum(1 for d in india_data if d.get("regime") == 2)

    w(f"**Regime summary:** {r4_count} R4 (explosive), {r2_count} R2 (volatile MR), {r1_count} R1 (calm)")
    w()
    w("| Ticker | Regime | Conf | RSI | ATR% | IV Rank | Signal | Commentary |")
    w("|--------|--------|------|-----|------|---------|--------|------------|")

    for d in india_data:
        if "error" in d:
            w(f"| {d['ticker']} | — | — | — | — | — | ERROR | {d['error']} |")
            continue
        ivr = f"{d['iv_rank']:.0f}%" if d.get("iv_rank") else "N/A"
        commentary = _india_commentary(d)
        w(f"| {'**' + d['ticker'] + '**' if d['signal'] in ('OPPORTUNITY', 'AVOID') else d['ticker']} "
          f"| {'**R' + str(d['regime']) + '**' if d['regime'] == 4 else 'R' + str(d['regime'])} "
          f"| {d['confidence']:.0%} | {d['rsi']:.1f} | {d['atr_pct']:.2f} "
          f"| {ivr} | {d['signal']} | {commentary} |")

    w()

    # India verdict
    if nifty and nifty["regime"] == 4:
        w("### INDIA VERDICT: WAIT")
        w()
        w(f"NIFTY is R4 at {nifty['confidence']:.0%} confidence. This is an explosive regime — "
          f"income structures on the index will face max-loss events. "
          f"Daily ATR of {nifty['atr_pct']:.1f}% implies \u00b1{nifty['price'] * nifty['atr_pct'] / 100:.0f} point swings.")
        w()
        w("**Do not deploy on indices until NIFTY transitions to R2.**")
    elif nifty and nifty["regime"] == 2:
        w("### INDIA VERDICT: SELECTIVE DEPLOYMENT")
        w()
        w("NIFTY is R2 — the correction is maturing. Premium is elevated. "
          "Deploy on indices with wider wings and R2 regime stop (3.0\u00d7 credit).")
    elif nifty and nifty["regime"] == 1:
        w("### INDIA VERDICT: FULL DEPLOYMENT")
        w()
        w("NIFTY is R1 — calm, mean-reverting. This is the ideal income environment. Deploy fully.")

    w()

    # ── UNIFIED ACTION TABLE ──
    w("### Action Table — India")
    w()
    w("> Each row = one ticker. Two action columns: what to do if you HOLD it, what to do if you want to DEPLOY fresh capital.")
    w("> Click any action in eTrading to instantly generate a scenario trade with full P&L, risk, and Greeks.")
    w()
    w("| Ticker | R | RSI | ATR% | If Holding | If Deploying Fresh Capital |")
    w("|--------|---|-----|------|-----------|---------------------------|")

    for d in india_data:
        if "error" in d:
            continue
        t, r, rsi, atr = d["ticker"], d["regime"], d["rsi"], d["atr_pct"]
        move = d["price"] * atr / 100

        # Holding action
        if r == 4:
            hold = f"**CLOSE income positions immediately.** Equity: hedge with NIFTY put or close trading positions. ATR = \u00b1{move:.0f}/day."
            deploy = f"**DO NOT ENTER.** R4 explosive. Wait for R2 transition."
        elif r == 3 and rsi < 30:
            hold = f"IC/spread: convert to diagonal or close tested side (1.5\u00d7 stop). Equity: hold with tight stop — deeply oversold but trending."
            deploy = f"**WAIT.** Oversold in downtrend = value trap risk. Need R2 regime first."
        elif r == 3:
            hold = f"IC/spread: close or convert. Equity: tighten stop to swing low. Do not add."
            deploy = f"**WAIT.** Trending down (R3). Not for income."
        elif r == 2 and rsi < 35:
            hold = f"IC/spread: hold with 3.0\u00d7 regime stop (wider than normal). Equity: sell covered call for income."
            deploy = f"**APPROACHING.** R2 + RSI {rsi:.0f}. Wait for RSI < 30 \u2192 credit spread, wider wings, 21 DTE."
        elif r == 2:
            hold = f"IC/spread: hold, 3.0\u00d7 stop. Equity: hold, sell CC if IV elevated."
            deploy = f"**MONITOR.** R2 but RSI {rsi:.0f} not oversold yet. Wait."
        elif r == 1 and rsi < 30:
            hold = f"**HOLD — textbook income environment.** Let theta work. Standard 2.0\u00d7 stop."
            deploy = f"**ENTER NOW.** R1 + RSI {rsi:.0f} oversold = ideal income entry. Credit spread or CSP. 1 lot, quarter Kelly."
        elif r == 1 and rsi < 40:
            hold = f"Hold. R1 calm, structures working as designed."
            deploy = f"**BUILDING.** R1 + RSI {rsi:.0f}. Wait for RSI < 30 to confirm oversold entry."
        elif r == 1:
            hold = f"Hold. Calm regime."
            deploy = f"Standard entry available. Check IV rank for premium adequacy."
        else:
            hold = f"Monitor."
            deploy = f"Evaluate."

        bold_t = f"**{t}**" if r in (1,) and rsi < 30 else t
        regime_fmt = f"**R{r}**" if r == 4 else f"R{r}"
        w(f"| {bold_t} | {regime_fmt} | {rsi:.0f} | {atr:.1f} | {hold} | {deploy} |")

    w()

    # Deployment phases
    w("### India Deployment Plan")
    w()
    w("| Phase | Trigger | Deploy | Instruments |")
    w("|-------|---------|--------|-------------|")
    w(f"| 0 | Now | INR 0 (0%) | 100% cash. Monitor daily. |")

    phase1_candidates = [d for d in india_data if d.get("regime") == 1 and d.get("rsi", 50) < 35]

    if phase1_candidates:
        names = ", ".join(d["ticker"] for d in phase1_candidates[:2])
        w(f"| 1 | R1 tickers RSI < 27 | INR {capital_india * 0.12:,.0f} (12%) | {names} credit spread |")

    w(f"| 2 | NIFTY R4 \u2192 R2 | INR {capital_india * 0.24:,.0f} (24%) | NIFTY IC + R2 stocks |")
    w(f"| 3 | NIFTY R2 \u2192 R1 | INR {capital_india * 0.24:,.0f} (24%) | Full NIFTY/BANKNIFTY IC |")
    w(f"| 4 | Full deployment | INR {capital_india * 0.24:,.0f} (24%) | Core equity + metals |")
    w(f"| R | Reserve | INR {capital_india * 0.16:,.0f} (16%) | Permanent cash buffer |")
    w()

    # ── Alerts ──
    w("---")
    w()
    w("## REGIME TRANSITION ALERTS TO SET")
    w()
    w("| Alert | Trigger | Action |")
    w("|-------|---------|--------|")
    w("| NIFTY R4 \u2192 R2 | Regime model transition | Begin India Phase 2 deployment |")
    w("| TCS RSI < 27 | Technical threshold (in R1) | India Phase 1 — first trade |")
    w("| Sentinel \u2192 RED | Crash escalation | Close ALL income positions |")
    w()

    # ── Footer ──
    _report_footer(lines, today, has_broker)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# US report
# ---------------------------------------------------------------------------

def generate_us_report(
    ma,
    us_data: list[dict],
    capital_us: float,
    sentinel_signal: str,
    sentinel_reasons: list[str],
    has_broker: bool,
) -> str:
    """Generate a self-contained US market research report."""
    today = date.today().strftime("%B %d, %Y")
    lines: list[str] = []

    def w(line=""):
        lines.append(line)

    w("# INCOME DESK RESEARCH — US Equity Income Strategy")
    w(f"### {today}")
    w()
    w(f"**Generated by:** income-desk Systematic Intelligence")
    w(f"**Data:** {'TastyTrade DXLink + ' if has_broker else ''}yfinance Historical OHLCV + HMM 4-State Regime Model")
    w(f"**Trust:** {'HIGH (broker connected)' if has_broker else 'MEDIUM (no broker — IV rank unavailable)'}")
    w()
    w("---")
    w()

    # ── MACRO ENVIRONMENT ──
    w("## MACRO ENVIRONMENT")
    w()

    # Crash Sentinel
    w("### Crash Sentinel")
    w()
    w(f"**Signal: {sentinel_signal.upper()}**")
    for r in sentinel_reasons:
        w(f"- {r}")
    w()

    # Black Swan
    try:
        bs = ma.black_swan.alert()
        w(f"**Black Swan Alert:** {bs.alert_level}")
        w(f"- Composite score: {bs.composite_score:.2f}")
        if hasattr(bs, 'indicators') and bs.indicators:
            for ind in bs.indicators[:5]:
                if hasattr(ind, 'name') and hasattr(ind, 'value'):
                    w(f"- {ind.name}: {ind.value}")
        w()
    except Exception:
        w("**Black Swan:** Unavailable (requires market data)")
        w()

    # Market context
    try:
        ctx = ma.context.assess()
        w(f"**Market Context:** {ctx.environment_label}")
        w(f"- Trading allowed: {'Yes' if ctx.trading_allowed else '**NO**'}")
        w(f"- Position size factor: {ctx.position_size_factor}")
        if hasattr(ctx, 'tradeable') and ctx.tradeable:
            w(f"- Options strategies available: {', '.join(ctx.tradeable.options_strategies[:5]) if ctx.tradeable.options_strategies else 'None'}")
        w()
    except Exception:
        pass

    # Rate risk — US instruments
    try:
        from income_desk.features.rate_risk import assess_rate_risk
        rate_tickers = ["TLT", "GLD", "XLF"]
        w("**Interest Rate Sensitivity:**")
        w()
        w("| Ticker | Rate Sensitivity | Impact per 100bp | Recommendation |")
        w("|--------|-----------------|------------------|----------------|")
        for rt in rate_tickers:
            try:
                rr = assess_rate_risk(rt)
                w(f"| {rt} | {rr.rate_sensitivity} | {rr.impact_per_100bp:.1%} | {rr.recommendation} |")
            except Exception:
                pass
        w()
    except Exception:
        pass

    # Macro calendar — US events only (FOMC, CPI, NFP, PCE, GDP)
    try:
        cal = ma.macro.calendar()
        if hasattr(cal, 'events') and cal.events:
            us_event_types = {"fomc", "cpi", "nfp", "pce", "gdp"}
            us_events = [e for e in cal.events if e.event_type.value in us_event_types][:8]
            if us_events:
                w("**Upcoming Macro Events:**")
                w()
                w("| Date | Event | Impact | Options Impact |")
                w("|------|-------|--------|----------------|")
                for e in us_events:
                    w(f"| {e.date.strftime('%b %d')} | {e.name} | {e.impact.value.upper()} | {e.options_impact} |")
                w()
    except Exception:
        pass

    # Key Benchmarks table
    w("### Key Benchmarks")
    w()
    w("| Index | Regime | Conf | RSI | ATR% | IV Rank | Condition |")
    w("|-------|--------|------|-----|------|---------|-----------|")

    for d in us_data:
        if d.get("ticker") in ("SPY", "QQQ", "IWM", "DIA", "GLD", "TLT") and "error" not in d:
            ivr = f"{d['iv_rank']:.0f}%" if d.get("iv_rank") else "—"
            r = d["regime"]
            if r == 4:
                condition = "EXPLOSIVE — no income"
            elif r == 3:
                condition = "TRENDING — avoid income"
            elif r == 2:
                cond_parts = ["HIGH VOL MR"]
                if d["rsi"] < 32:
                    cond_parts.append("approaching oversold")
                condition = " — ".join(cond_parts)
            elif r == 1:
                cond_parts = ["CALM"]
                if d["rsi"] < 30:
                    cond_parts.append("oversold = opportunity")
                elif d["rsi"] < 40:
                    cond_parts.append("building")
                condition = " — ".join(cond_parts)
            else:
                condition = "—"
            regime_fmt = f"**R{r}**" if r == 4 else f"R{r}"
            w(f"| {d['ticker']} | {regime_fmt} | {d['confidence']:.0%} | {d['rsi']:.1f} | {d['atr_pct']:.2f} | {ivr} | {condition} |")

    w()

    # Market narrative — US
    us_r4 = sum(1 for d in us_data if d.get("regime") == 4)
    us_r1 = sum(1 for d in us_data if d.get("regime") == 1)

    w("### Market Narrative")
    w()
    if us_r4 >= 3:
        w("**US is in crisis.** Multiple sectors in R4. Broad-based liquidation underway. "
          "100% cash until regime transitions begin.")
        w()
    elif us_r4 >= 1:
        w(f"**US is correcting but not crashing.** {us_r4} sector(s) in R4, but {us_r1} in R1 — "
          f"select income opportunities exist in decoupled sectors.")
        w()
    else:
        w("**US is stable.** No R4 regimes detected. Standard income deployment appropriate.")
        w()

    spy = next((d for d in us_data if d.get("ticker") == "SPY" and "error" not in d), None)
    gld = next((d for d in us_data if d.get("ticker") == "GLD" and "error" not in d), None)
    if spy and gld:
        if spy["regime"] >= 2 and gld.get("iv_rank", 0) and gld["iv_rank"] > 60:
            w(f"**Notable:** GLD IV Rank at {gld['iv_rank']:.0f}% (68th+ percentile) — gold volatility is at extremes. "
              f"When GLD transitions from R{gld['regime']} to R2, premium will be 2-3\u00d7 normal. This is the single highest-premium "
              f"opportunity in the current universe. Set regime transition alert.")
            w()

    w("---")
    w()

    # ── Regime scan table ──
    w(f"## US MARKET (Capital: ${capital_us:,.0f})")
    w()

    r4_count = sum(1 for d in us_data if d.get("regime") == 4)
    r1_count = sum(1 for d in us_data if d.get("regime") == 1)

    w(f"**Regime summary:** {r4_count} R4, {r1_count} R1 (tradeable now)")
    w()
    w("| Ticker | Regime | Conf | RSI | ATR% | IV Rank | Signal | Commentary |")
    w("|--------|--------|------|-----|------|---------|--------|------------|")

    for d in us_data:
        if "error" in d:
            w(f"| {d['ticker']} | — | — | — | — | — | ERROR | {d['error']} |")
            continue
        ivr = f"{d['iv_rank']:.0f}%" if d.get("iv_rank") else "N/A"
        commentary = _us_commentary(d)
        w(f"| {'**' + d['ticker'] + '**' if d['signal'] in ('OPPORTUNITY', 'AVOID') else d['ticker']} "
          f"| {'**R' + str(d['regime']) + '**' if d['regime'] == 4 else 'R' + str(d['regime'])} "
          f"| {d['confidence']:.0%} | {d['rsi']:.1f} | {d['atr_pct']:.2f} "
          f"| {ivr} | {d['signal']} | {commentary} |")

    w()

    # ── UNIFIED ACTION TABLE (US) ──
    w("### Action Table — US")
    w()
    w("> Each row = one ticker. Two action columns: what to do if you HOLD it, what to do if you want to DEPLOY fresh capital.")
    w("> Click any action in eTrading to instantly generate a scenario trade with full P&L, risk, and Greeks.")
    w()
    w("| Ticker | R | RSI | IVR | If Holding | If Deploying Fresh Capital |")
    w("|--------|---|-----|-----|-----------|---------------------------|")

    for d in us_data:
        if "error" in d:
            continue
        t, r, rsi, atr = d["ticker"], d["regime"], d["rsi"], d["atr_pct"]
        ivr = d.get("iv_rank", 0) or 0
        ivr_str = f"{ivr:.0f}%" if ivr else "—"

        if r == 4:
            hold = f"**CLOSE income immediately.** Equity: add SPY put hedge or close. ATR {atr:.1f}%."
            deploy = f"**DO NOT ENTER.** R4 explosive."
        elif r == 3 and rsi < 30:
            hold = f"IC: close or convert to diagonal. Equity: hold with tight stop — deeply oversold but trending."
            deploy = f"**WATCH.** Oversold in trend. Wait for R2. {'IVR ' + str(int(ivr)) + '% — premium will be rich when regime turns.' if ivr > 50 else ''}"
        elif r == 3:
            hold = f"IC: close tested side, 1.5\u00d7 stop. Equity: tighten stop."
            deploy = f"**WAIT.** R3 trending.{' IVR ' + str(int(ivr)) + '% — set alert for R2 transition.' if ivr > 45 else ''}"
        elif r == 2 and rsi < 32:
            hold = f"IC: hold, 3.0\u00d7 regime stop. Equity: sell CC if IVR > 40%.{' IVR ' + str(int(ivr)) + '%.' if ivr else ''}"
            deploy = f"**APPROACHING.** R2 + RSI {rsi:.0f}. IC with wider wings (1.5\u00d7 ATR), 21 DTE, 3\u00d7 stop.{' IVR ' + str(int(ivr)) + '% = good premium.' if ivr > 40 else ''}"
        elif r == 2:
            hold = f"IC: hold, 3.0\u00d7 stop. Equity: hold."
            deploy = f"**MONITOR.** R2 but RSI {rsi:.0f} not oversold. Wait."
        elif r == 1 and ivr > 40 and rsi < 40:
            hold = f"**HOLD — ideal.** IC: standard 2.0\u00d7 stop. Equity: sell CC (IVR {ivr:.0f}% = premium available)."
            deploy = f"**ENTER NOW.** R1 + IVR {ivr:.0f}% + RSI {rsi:.0f}. IC or credit spread. Half Kelly."
        elif r == 1 and ivr > 40:
            hold = f"Hold. R1 calm. Sell CC on equity (IVR {ivr:.0f}%)."
            deploy = f"**AVAILABLE.** R1 + IVR {ivr:.0f}%. Standard IC entry."
        elif r == 1:
            hold = f"Hold. R1 calm."
            deploy = f"**R1 but IVR {ivr:.0f}% low** — thin premium. Only if credit > $0.80 on 5-wide."
        else:
            hold = f"Monitor."
            deploy = f"Evaluate."

        bold_t = f"**{t}**" if r == 1 and ivr > 40 else t
        regime_fmt = f"**R{r}**" if r == 4 else f"R{r}"
        w(f"| {bold_t} | {regime_fmt} | {rsi:.0f} | {ivr_str} | {hold} | {deploy} |")

    w()

    # US deployment
    w("### US Deployment Plan")
    w()
    w("| Phase | Trigger | Deploy | Instruments |")
    w("|-------|---------|--------|-------------|")

    r1_names = [d["ticker"] for d in us_data if d.get("regime") == 1 and d.get("iv_rank", 0) and d["iv_rank"] > 35]
    if r1_names:
        w(f"| 0 | Now | ${capital_us * 0.15:,.0f} (15%) | {', '.join(r1_names[:3])} IC/spread |")
    else:
        w(f"| 0 | Now | $0 (0%) | No R1 + adequate IV — wait |")

    w(f"| 1 | SPY RSI < 28 | ${capital_us * 0.25:,.0f} (25%) | SPY IC (R2 wider wings) |")
    w(f"| 2 | GLD/IWM R3 \u2192 R2 | ${capital_us * 0.30:,.0f} (30%) | High-IV names in R2 |")
    w(f"| 3 | QQQ R3 \u2192 R2 | ${capital_us * 0.20:,.0f} (20%) | Tech sector recovery |")
    w(f"| R | Reserve | ${capital_us * 0.10:,.0f} (10%) | Permanent cash buffer |")
    w()

    # ── Alerts ──
    w("---")
    w()
    w("## REGIME TRANSITION ALERTS TO SET")
    w()
    w("| Alert | Trigger | Action |")
    w("|-------|---------|--------|")
    w("| GLD R3 \u2192 R2 | Regime + IV rank > 60% | US Phase 2 — extraordinary premium |")
    w("| SPY RSI < 28 | Technical threshold | US Phase 1 expansion |")
    w("| Sentinel \u2192 RED | Crash escalation | Close ALL income positions |")
    w()

    # ── Footer ──
    _report_footer(lines, today, has_broker)

    return "\n".join(lines)


def _india_commentary(d: dict) -> str:
    t, r, rsi, atr = d["ticker"], d["regime"], d["rsi"], d["atr_pct"]
    if r == 4:
        return f"Explosive. ATR {atr:.1f}% = violent moves. No exposure."
    if r == 3 and rsi < 30:
        return f"Deeply oversold but trend is down. Wait for R2."
    if r == 3:
        return f"Trending down. Not for income."
    if r == 1 and rsi < 30:
        return f"Oversold in calm regime — textbook income entry."
    if r == 1:
        return f"Calm. Standard income structures."
    if r == 2 and rsi < 35:
        return f"Approaching oversold in high-vol MR. Wider wings, shorter DTE."
    if r == 2:
        return f"High-vol MR. Premium elevated. Patience."
    return ""


def _us_commentary(d: dict) -> str:
    t, r, rsi, ivr = d["ticker"], d["regime"], d["rsi"], d.get("iv_rank") or 0
    if r == 4:
        return f"Explosive. Avoid."
    if r == 3 and rsi < 35:
        return f"Oversold in trend. Watch for R2 transition."
    if r == 3:
        return f"Trending. Wait."
    if r == 1 and ivr and ivr > 40:
        return f"R1 + IV rank {ivr:.0f}% — tradeable now."
    if r == 1:
        return f"Calm but IV rank {'low' if ivr and ivr < 30 else 'N/A'} — thin premium."
    if r == 2 and rsi < 32:
        return f"Approaching oversold in R2. Prepare entry."
    if r == 2:
        return f"R2 mean-reverting. Wider wings."
    return ""


def main():
    parser = argparse.ArgumentParser(description="Generate income-desk research report")
    parser.add_argument("--market", choices=["india", "us", "both"], required=True, help="Market to generate report for")
    parser.add_argument("--capital-india", type=float, default=5_000_000, help="India capital in INR")
    parser.add_argument("--capital-us", type=float, default=100_000, help="US capital in USD")
    parser.add_argument("--broker", action="store_true", help="Use live broker data")
    parser.add_argument("--output", type=str, default=None, help="Save to file (default: print)")
    args = parser.parse_args()

    # Connect data
    if args.broker:
        from income_desk.cli._broker import connect_broker
        md, mm, acct, wl = connect_broker(is_paper=False)
        if md is None:
            print("Broker connection failed.")
            return
        from income_desk import MarketAnalyzer, DataService
        ma = MarketAnalyzer(data_service=DataService(), market_data=md, market_metrics=mm)
        has_broker = True
    else:
        from income_desk import MarketAnalyzer, DataService
        ma = MarketAnalyzer(data_service=DataService())
        has_broker = False

    # Scan markets
    india_data = None
    us_data = None

    if args.market in ("india", "both"):
        print("Scanning India market...", file=sys.stderr)
        india_data = scan_market(ma, flatten(INDIA_UNIVERSE), "India")

    if args.market in ("us", "both"):
        print("Scanning US market...", file=sys.stderr)
        us_data = scan_market(ma, flatten(US_UNIVERSE), "US")

    # Crash sentinel (US-based)
    sentinel_signal = "GREEN"
    sentinel_reasons = ["All systems normal"]
    try:
        from income_desk.features.crash_sentinel import assess_crash_sentinel
        sentinel_regimes = {}
        sentinel_ivr = {}
        for t in ["SPY", "QQQ", "IWM", "GLD", "TLT"]:
            try:
                r = ma.regime.detect(t)
                sentinel_regimes[t] = {
                    "regime_id": r.regime.value,
                    "confidence": r.confidence,
                    "r4_prob": r.regime_probabilities.get(4, 0) if r.regime_probabilities else 0,
                }
                m = ma.quotes.get_metrics(t) if has_broker else None
                if m and hasattr(m, "iv_rank") and m.iv_rank:
                    sentinel_ivr[t] = m.iv_rank
            except Exception:
                pass

        if sentinel_regimes:
            tech = ma.technicals.snapshot("SPY")
            report = assess_crash_sentinel(
                sentinel_regimes, sentinel_ivr,
                spy_atr_pct=tech.atr_pct, spy_rsi=tech.rsi.value,
            )
            sentinel_signal = report.signal.value
            sentinel_reasons = report.reasons
    except Exception:
        pass

    # Generate and output reports
    research_dir = Path("docs/research")
    research_dir.mkdir(parents=True, exist_ok=True)

    if args.market in ("india", "both") and india_data:
        india_report = generate_india_report(ma, india_data, args.capital_india, has_broker)

        if args.output:
            path = Path(args.output.replace('.md', '-india.md'))
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(india_report, encoding="utf-8")
            print(f"India report saved: {path}", file=sys.stderr)
        else:
            print(india_report)

        dated_path = research_dir / f"{date.today().isoformat()}-india-deployment.md"
        dated_path.write_text(india_report, encoding="utf-8")
        print(f"Archived: {dated_path}", file=sys.stderr)

    if args.market in ("us", "both") and us_data:
        us_report = generate_us_report(
            ma, us_data, args.capital_us,
            sentinel_signal, sentinel_reasons, has_broker,
        )

        if args.output:
            path = Path(args.output.replace('.md', '-us.md'))
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(us_report, encoding="utf-8")
            print(f"US report saved: {path}", file=sys.stderr)
        else:
            print(us_report)

        dated_path = research_dir / f"{date.today().isoformat()}-us-deployment.md"
        dated_path.write_text(us_report, encoding="utf-8")
        print(f"Archived: {dated_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
